spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3.1415926
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 10.112.3.100 # redis所在的主机IP地址
    port: 6379
  rabbitmq:
    addresses: 10.112.3.100
    port: 5672
    username: guest
    password: guest
#    password: 如果redis设置了密码，这里还需要配置密码
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
#logging:
#  pattern:
#    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 1200 # 单位是秒，session失效时间设置成20分钟
